apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: billing-handler-22000
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/billing-handler-22000
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
